from django.db import models

class Funcionario(models.Model):
    nome_completo = models.CharField(max_length=255)
    data_nascimento = models.DateField()
    rg = models.CharField(max_length=20)
    cpf = models.CharField(max_length=14)
    endereco_residencial = models.CharField(max_length=255)
    telefone = models.CharField(max_length=20)
    email = models.EmailField()
    documento_identidade = models.CharField(max_length=20)
    carteira_trabalho = models.CharField(max_length=20)
    comprovante_residencia = models.CharField(max_length=255)
    contato_emergencia_nome = models.CharField(max_length=255)
    contato_emergencia_relacao = models.CharField(max_length=50)
    contato_emergencia_telefone = models.CharField(max_length=20)
    formacao_academica = models.CharField(max_length=255)
    historico_profissional = models.TextField()
    numero_conta_bancaria = models.CharField(max_length=20)
    agencia_bancaria = models.CharField(max_length=10)
    banco = models.CharField(max_length=100)
    estado_civil = models.CharField(max_length=50)
    dependentes = models.IntegerField()
    informacoes_fiscais = models.TextField()
    foto = models.ImageField(upload_to='fotos/', null=True, blank=True)
    profissao = models.CharField(max_length=100)
    departamento = models.CharField(max_length=100)
    data_inicio_profissao = models.DateField()
    data_termino_profissao = models.DateField(null=True, blank=True)
    trabalhando_em = models.CharField(max_length=255, null=True, blank=True)
    horario_de_trabalho_inicio = models.TimeField()
    horario_de_trabalho_fim = models.TimeField()
    intervalo = models.TimeField()
    numero_casa = models.CharField(max_length=10)
    carteira_de_trabalho = models.CharField(max_length=20)
    passaporte = models.CharField(max_length=20)
    alegias = models.CharField(max_length=255)
    condicoes_medicas = models.CharField(max_length=255)
    cargo = models.CharField(max_length=100)
    salario = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.nome_completo